import React from 'react';
import { MOCK_REPORTS } from '../mockData';
import { FileText, Download, Printer, RefreshCw } from 'lucide-react';

const ReportsView: React.FC = () => {
  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <div>
          <h2 className="text-2xl font-bold text-white flex items-center gap-2">
             <FileText className="h-6 w-6 text-slate-400" />
             Relatórios PDF
          </h2>
          <p className="text-slate-400 text-sm">Automated Reports generated by AI Engine</p>
        </div>
        <button className="flex items-center gap-2 px-4 py-2 bg-primary-600 hover:bg-primary-700 text-white rounded-lg transition-colors">
            <RefreshCw className="h-4 w-4" />
            <span>Generate Now</span>
        </button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
         {MOCK_REPORTS.map((rep) => (
             <div key={rep.id} className="bg-slate-900 border border-slate-800 rounded-xl p-6 hover:border-slate-600 transition-colors group">
                 <div className="flex justify-between items-start mb-4">
                     <div className="p-3 bg-slate-800 rounded-lg group-hover:bg-slate-700 transition-colors">
                        <FileText className="h-8 w-8 text-slate-400" />
                     </div>
                     <span className={`px-2 py-1 rounded text-xs font-bold ${
                         rep.status === 'Ready' ? 'bg-green-500/10 text-green-400' : 'bg-yellow-500/10 text-yellow-400'
                     }`}>
                         {rep.status}
                     </span>
                 </div>
                 <h3 className="text-lg font-bold text-white mb-1">{rep.title}</h3>
                 <p className="text-sm text-slate-400 mb-4">{rep.type} • {rep.generatedAt}</p>
                 
                 <div className="flex justify-between items-center pt-4 border-t border-slate-800">
                     <span className="text-xs text-slate-500 font-mono">{rep.size}</span>
                     {rep.status === 'Ready' && (
                         <div className="flex gap-2">
                             <button className="p-2 hover:bg-slate-800 rounded text-slate-400 hover:text-white" title="Print">
                                 <Printer className="h-4 w-4" />
                             </button>
                             <button className="p-2 bg-slate-800 hover:bg-slate-700 rounded text-white flex items-center gap-2" title="Download">
                                 <Download className="h-4 w-4" />
                                 <span className="text-xs font-semibold">PDF</span>
                             </button>
                         </div>
                     )}
                 </div>
             </div>
         ))}
      </div>
    </div>
  );
};

export default ReportsView;